--CREATE DATABASE MORADA_DA_PAZDB
--GO
--USE MORADA_DA_PAZDB
--CREATE TABLE ESPECIALIZACAO_USUARIO (ID INT PRIMARY KEY IDENTITY NOT NULL,
--									 DESCRICAO TEXT NOT NULL);

--CREATE TABLE UNIDADE_RESIDENCIAL (ID INT PRIMARY KEY IDENTITY NOT NULL,
--								  NUMERO_UNIDADE VARCHAR(8) NOT NULL, 
--								  DESCRICAO TEXT);

--CREATE TABLE USUARIO (ID INT PRIMARY KEY IDENTITY NOT NULL,
--					  EMAIL VARCHAR(30), 
--					  LOGIN_ VARCHAR(30) NOT NULL, 
--					  SENHA VARCHAR(500) NOT NULL, 
--					  NOME_COMPLETO VARCHAR(100) NOT NULL,
--					  IDADE INT NOT NULL,
--					  ID_UNIDADE_RESIDENCIAL INT REFERENCES UNIDADE_RESIDENCIAL(ID) NOT NULL,
--					  ID_ESPECIALIZACAO INT REFERENCES ESPECIALIZACAO_USUARIO(ID) NOT NULL);

--CREATE TABLE ADVERTENCIA (ID INT PRIMARY KEY IDENTITY NOT NULL, 
--						  DESCRICAO TEXT NOT NULL);

--CREATE TABLE MULTA (ID INT PRIMARY KEY IDENTITY NOT NULL, 
--					DESCRICAO TEXT, 
--					PRECO FLOAT NOT NULL);

--CREATE TABLE OCORRENCIA (ID INT PRIMARY KEY IDENTITY NOT NULL, 
--						SITUACAO VARCHAR(30) DEFAULT ('ABERTO'), 
--						NUMERO_OCORRENCIA VARCHAR(30) NOT NULL, 
--						DESCRICAO TEXT NOT NULL,
--						TIPOPUBLICO INT DEFAULT (0),
--						ID_USUARIO INT REFERENCES USUARIO(ID) NOT NULL,
--						ID_UNIDADE_RESIDENCIAL INT REFERENCES UNIDADE_RESIDENCIAL(ID));

--CREATE TABLE OCORRENCIA_ADVERTENCIA (ID_OCORRENCIA INT REFERENCES OCORRENCIA(ID) NOT NULL,
--									 ID_ADVERTENCIA INT REFERENCES ADVERTENCIA(ID) NOT NULL
--									 );

--CREATE TABLE OCORRENCIA_MULTA (ID_OCORRENCIA INT REFERENCES OCORRENCIA(ID) NOT NULL,
--							   ID_MULTA INT REFERENCES MULTA(ID) NOT NULL,
--							   VALOR_TOTAL FLOAT NOT NULL,
--							   );




INSERT INTO UNIDADE_RESIDENCIAL (NUMERO_UNIDADE, DESCRICAO) VALUES (0, 'NENHUMA'),(101, 'PRIMEIRO ANDAR'),(102, 'PRIMERIO ANDAR'),(201, 'SEGUNDO ANDAR'),(202, 'SEGUNDO ANDAR');

INSERT INTO ESPECIALIZACAO_USUARIO (DESCRICAO) VALUES ('ADMIN'),('MORADOR');

INSERT INTO USUARIO (LOGIN_,SENHA,NOME_COMPLETO,ID_UNIDADE_RESIDENCIAL, ID_ESPECIALIZACAO ) 
VALUES ('ADMIN', 'ADMIN', 'ADM', 1, 1)

SELECT * FROM OCORRENCIA;

SELECT * FROM USUARIO

SELECT ID, SITUACAO, NUMERO_OCORRENCIA, DESCRICAO, ID_USUARIO, ID_UNIDADE_RESIDENCIAL FROM OCORRENCIA

ALTER TABLE OCORRENCIA ADD TIPOPUBLICO INT DEFAULT (0);

UPDATE OCORRENCIA SET TIPOPUBLICO = 0;

INSERT INTO OCORRENCIA (SITUACAO,NUMERO_OCORRENCIA ,DESCRICAO, ID_USUARIO, ID_UNIDADE_RESIDENCIAL, TIPOPUBLICO)
 VALUES (NULL, 1042512759, 'CAGUEI NA PISCINA', 1, 1, 1)
USE MORADA_DA_PAZDB
SELECT * FROM OCORRENCIA;

INSERT INTO ESPECIALIZACAO_USUARIO (DESCRICAO) VALUES ('MORADOR');
SELECT * FROM ESPECIALIZACAO_USUARIO;
UPDATE OCORRENCIA SET ID_USUARIO = 2 WHERE ID = 4

SELECT * FROM MULTA;
